// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBof46MAPsDmk9crS2QgxbbBDcXLAz2lyg',
    appId: '1:552015572299:web:517e3fc140d14ef6530cce',
    messagingSenderId: '552015572299',
    projectId: 'lets-learn-b6005',
    authDomain: 'lets-learn-b6005.firebaseapp.com',
    storageBucket: 'lets-learn-b6005.appspot.com',
    measurementId: 'G-0F6DY8E3M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmranU7I_f9cWeqni6J5Wis4cp-q_RICU',
    appId: '1:552015572299:android:33ad51d5a10b5fe3530cce',
    messagingSenderId: '552015572299',
    projectId: 'lets-learn-b6005',
    storageBucket: 'lets-learn-b6005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ6tig38322TcvOE4pfBxz2QK7TFXqTpc',
    appId: '1:552015572299:ios:528946cfb4317848530cce',
    messagingSenderId: '552015572299',
    projectId: 'lets-learn-b6005',
    storageBucket: 'lets-learn-b6005.appspot.com',
    iosBundleId: 'com.slthiri.boostESkills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ6tig38322TcvOE4pfBxz2QK7TFXqTpc',
    appId: '1:552015572299:ios:5cc0000d6427f0fe530cce',
    messagingSenderId: '552015572299',
    projectId: 'lets-learn-b6005',
    storageBucket: 'lets-learn-b6005.appspot.com',
    iosBundleId: 'com.slthiri.boostESkills.RunnerTests',
  );
}
